---
#
# Prepares system for Deluge.
#

- name: Create UNIX group
  group:
    name: "{{ deluge.user }}"
    system: yes
    state: present

- name: Create UNIX user
  user:
    name: "{{ deluge.user }}"
    group: "{{ deluge.user }}"
    home: "{{ deluge.home }}"
    createhome: yes
    skeleton: yes
    system: yes
    state: present
