---
#
# Configures time and synchronization.
#

- name: Set timezone to Etc/UTC
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/timezone
    force: yes
    state: link
  register: result

- name: Reconfigure tzdata
  command: dpkg-reconfigure -f noninterractive tzdata
  when: result is changed

- name: Install NTP daemon
  apt:
    name: ntp
    state: present

- name: Start NTP daemon
  service:
    name: ntp
    enabled: yes
    state: started
