---
#
# Configures OpenTracker.
#

- name: Create config directory
  file:
    path: "{{ opentracker.conf }}"
    state: directory
    mode: 0755

- name: Copy config file
  template:
    src: config
    dest: "{{ opentracker.conf }}/config"
    mode: 0644
  notify: Restart OpenTracker

- name: Copy whitelist file
  copy:
    src: whitelist
    dest: "{{ opentracker.conf }}/whitelist"
    mode: 0644
  notify: Restart OpenTracker

- name: Install service
  template:
    src: service
    dest: /etc/systemd/system/opentracker.service
    mode: 0644
  notify: Restart OpenTracker
