---
#
# Builds and installs OpenTracker.
#

- name: Clone OpenTracker
  git:
    repo: git://erdgeist.org/opentracker
    dest: "{{ opentracker.repo }}"
    force: yes
  become: yes
  become_user: "{{ opentracker.user }}"
  register: result

- name: Build OpenTracker
  make:
    chdir: "{{ opentracker.repo }}"
    target: opentracker
  environment:
    FEATURES: "-DWANT_ACCESSLIST_WHITE"
  become: yes
  become_user: "{{ opentracker.user }}"
  when: result is changed

- name: Install OpenTracker
  copy:
    remote_src: yes
    src: "{{ opentracker.repo }}/opentracker"
    dest: /usr/local/bin/opentracker
    mode: 0755
    owner: root
    group: root
  notify: Restart OpenTracker
  when: result is changed

- name: Clean OpenTracker
  make:
    chdir: "{{ opentracker.repo }}"
    target: clean
  become: yes
  become_user: "{{ opentracker.user }}"
  when: result is changed
